<?xml version="1.0"?>
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="rod_length" value="1.0"/>


    <link name="world"/>

    <joint name="horizontal_joint" type="prismatic">
        <origin xyz="0 0 ${rod_length+0.1}" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="-10" upper="10" effort="100" velocity="1"/>
        <dynamics damping="0.1"/>
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.5 0.2 0.1"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <joint name="pivot_joint" type="continuous">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="rod_link"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.1"/>
    </joint>

    <link name="rod_link">
        <visual>
            <origin xyz="0 0 ${rod_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.02" length="${rod_length}"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 ${rod_length/2}" rpy="0 0 0"/>
            <mass value="0.001"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>

    <joint name="ball_joint" type="fixed">
        <origin xyz="0 0 ${rod_length}" rpy="0 0 0"/>
        <parent link="rod_link"/>
        <child link="ball_link"/>
    </joint>

    <link name="ball_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="0.1"/>
            </geometry>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.5"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
    </link>

    <xacro:include filename="$(find inverted_pendulum_description)/urdf/ip.gazebo.xacro"/>

</robot>