ip:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  horizontal_joint_controller:
    type: effort_controllers/JointEffortController
    joint: horizontal_joint
  